name: CI

on:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Pint
        run: vendor/bin/pint --test
      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'

  tests:
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: pcov
      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Tests
        run: ./vendor/bin/pest -p

#  versioning:
#    name: Create New Version
#    needs: [tests, quality]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Setup Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: 20
#      - name: Install Plugins
#        run: npm i @semantic-release/changelog @semantic-release/git @semantic-release/exec -D
#      - name: Create Release
#        run: npx semantic-release@^20.1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
